import Head from "next/head";
import styles from "styles/Home.module.css";
import { Banner } from "components/banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <Banner />

          <div className={styles.ctas}>App for living waters</div>
        </main>
      </div>
    </>
  );
}
